spring:
  data:
    mongodb:
     # authentication-database: dbAdmin
      #username: ${MONGO_USERNAME}
      #password: ${MONGO_PASSWORD}
      database: notesdb_07
      port: 27017
      host: localhost
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411/  
    locator:
      discovery:
        enable: true
  #Rabbit MQ Server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
server:
  port: 9200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
